kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "3scale-build-pipeline"
spec:
  source:
      git:
        uri: https://github.com/srinivma1/3scale-jenkins-pipeline-demo.git
  strategy:
    jenkinsPipelineStrategy:
        jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
